import React, { Component } from 'react';
import './intro.css';
class Intro extends Component {
    state = {  }
    render() { 
        return ( 
            <div className="intro-container">
                <h1>intro</h1>
                <img src="https://picsum.photos/200/300" alt="" />
                <p>ABAEHNGNEAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNNGNEAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNNGNEAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNNGNEAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNNGNEAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNNGNEAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNNGNEAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGAKJNGEAKJNGKJNAEKGNEKJANGJKANEJKGN</p>
            </div>
         );
    }
}
 
export default Intro;